# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'phone' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for phone
    pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'React' , :subspecs => [
        'ART',
        'RCTImage',
        'RCTNetwork',
        'RCTLinkingIOS',
        'RCTActionSheet',
        'RCTAdSupport',
        'RCTGeolocation',
        'RCTPushNotification',
        'RCTSettings',
        'RCTVibration',
        'RCTText',
        'RCTWebSocket'
    ], :path => '../node_modules/react-native'

  pod 'react-native-fbsdk', :subspecs => [
    'Core',
    'Login',
    'Share',
  ], :path => '../node_modules/react-native-fbsdk/iOS'

  target 'phoneTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
